image: python:3.7.4-alpine3.10

definitions:
  services:
    docker:
      memory: 7168

  steps:
    -step: &build-image
      name: Push to ECR
      size: 2x
      services:
        - docker
      script:
        - TAG=${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}
        - TAG_LATEST=${BITBUCKET_BRANCH}-latest
        - docker build -t ${IMAGE}:$TAG -t ${IMAGE}:$TAG_LATEST .
        - pipe: atlassian/aws-ecr-push-image:2.4.2
          variables:
            AWS_ACCESS_KEY_ID: $AWS_KEY
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET
            AWS_DEFAULT_REGION: us-east-2
            IMAGE_NAME: ${IMAGE}
            TAGS: '${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER} ${BITBUCKET_BRANCH}-latest'

options:
  docker: true
  size: 2x

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step:
              image: node:20
              name: Lint
              size: 2x
              script:
                - cp .env.example .env
                - npm install
                - npm run lint
                - npm run prettier
                - npm run format
              caches:
                - node
  branches:
    "main":
      - stage:
          name: Build with Docker
          deployment: Prd
          steps:
            - step: *build-image
            - step:
                name: Deploy to Prd
                script:
                  - pipe: atlassian/aws-eks-kubectl-run:1.2.0
                    variables:
                      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_TERRAFORM}
                      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_TERRAFORM}
                      AWS_DEFAULT_REGION: "us-east-2"
                      CLUSTER_NAME: ${CLUSTER_NAME}
                      KUBECTL_COMMAND: "set"
                      KUBECTL_ARGS:
                        - "image"
                        - "--namespace=prd"
                        - "deployment/backend-countries-now"
                        - "backend-countries-now=${IMAGE_URL}:${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}"
                      DEBUG: "true"
#    "qa":
#      - stage:
#          name: Build with Docker
#          deployment: QA
#          steps:
#            - step: *build-image
#            - step:
#                name: Deploy to QA
#                script:
#                  - pipe: atlassian/aws-eks-kubectl-run:1.2.0
#                    variables:
#                      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_TERRAFORM}
#                      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_TERRAFORM}
#                      AWS_DEFAULT_REGION: "us-east-2"
#                      CLUSTER_NAME: ${CLUSTER_NAME}
#                      KUBECTL_COMMAND: "set"
#                      KUBECTL_ARGS:
#                        - "image"
#                        - "--namespace=qa"
#                        - "deployment/backend-auth"
#                        - "backend-auth=${IMAGE_URL}:${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}"
#                      DEBUG: "true"
#
#    "stg":
#      - stage:
#          name: Build with Docker
#          deployment: Stg
#          steps:
#            - step: *build-image
#            - step:
#                name: Deploy to Staging
#                script:
#                  - pipe: atlassian/aws-eks-kubectl-run:1.2.0
#                    variables:
#                      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_TERRAFORM}
#                      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_TERRAFORM}
#                      AWS_DEFAULT_REGION: "us-east-2"
#                      CLUSTER_NAME: ${CLUSTER_NAME}
#                      KUBECTL_COMMAND: "set"
#                      KUBECTL_ARGS:
#                        - "image"
#                        - "--namespace=stg"
#                        - "deployment/backend-auth"
#                        - "backend-auth=${IMAGE_URL}:${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}"
#                      DEBUG: "true"